# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

platform :ios, ‘7.0’

target 'FastCode' do

	pod 'AFNetworking', '~> 3.0'
	pod 'SDWebImage', '~>3.8'
	pod 'FMDB'
	pod 'MBProgressHUD', '~> 0.9.2'

end

